/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.PengaduanKontrol;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zubaidi
 */
public class BerandaFormMasyarakat extends javax.swing.JInternalFrame {
    
    PengaduanKontrol pk;
    DefaultTableModel dtm;
    
    
    
    /**
     * Creates new form BerandaFormMasyarakat
     */
    public BerandaFormMasyarakat() {
        initComponents();
        pk = new PengaduanKontrol();
        
        tbBeranda.getTableHeader().setBackground(new Color(0,49,163));
        tbBeranda.getTableHeader().setForeground(new Color(255,255,255));
        
        tampilBeranda();
        
        mati();

    }
    
    private void tampilBeranda() {
        try {
            dtm = (DefaultTableModel) tbBeranda.getModel();
            dtm.setRowCount(0);
            this.aturTabel();
            pk.tampilLaporanDitanggapi(dtm);
            tbBeranda.setModel(dtm);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void mati() {
        
        txtPengaduan.setEditable(false);
        txtTanggapan.setEditable(false);
    }
    
    //    ukuran tabel
    private void aturTabel(){
        tbBeranda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbBeranda.getColumnModel().getColumn(0).setPreferredWidth(30); //No
        tbBeranda.getColumnModel().getColumn(1).setPreferredWidth(85); //No Tangg
        tbBeranda.getColumnModel().getColumn(2).setPreferredWidth(85); //Id Lap
        tbBeranda.getColumnModel().getColumn(3).setPreferredWidth(250); //Nama
        tbBeranda.getColumnModel().getColumn(4).setPreferredWidth(85); //Tgl
        tbBeranda.getColumnModel().getColumn(5).setPreferredWidth(110); //foto
    }
    
    private void setLaporan(){
        txtNamaPengadu.setText(tbBeranda.getValueAt(tbBeranda.getSelectedRow(), 3).toString());
        txtTgl.setText(tbBeranda.getValueAt(tbBeranda.getSelectedRow(), 4).toString());
        try {
            ResultSet rs = pk.isiLaporanPengaduan(tbBeranda.getValueAt(tbBeranda.getSelectedRow(), 1).toString());
            while(rs.next()){
                txtPengaduan.setText(rs.getString("isi"));
                txtTanggapan.setText(rs.getString("tanggapan"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(BerandaFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setFoto(){
        try {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            String path = new File(".").getCanonicalPath();
            Image image = toolkit.getImage(path+"/image/"+tbBeranda.getValueAt(tbBeranda.getSelectedRow(), 5));
            Image ImageResize = image.getScaledInstance(205, 235, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(ImageResize);
            lblFoto.setIcon(icon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBeranda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaPengadu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTgl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTanggapan = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPengaduan = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 450));

        tbBeranda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No. Tang.", "ID. Lap.", "Nama", "Tanggal", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBeranda.setRowHeight(25);
        tbBeranda.setRowMargin(0);
        tbBeranda.setSelectionBackground(new java.awt.Color(102, 255, 0));
        tbBeranda.setShowVerticalLines(false);
        tbBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBerandaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBeranda);
        if (tbBeranda.getColumnModel().getColumnCount() > 0) {
            tbBeranda.getColumnModel().getColumn(0).setResizable(false);
            tbBeranda.getColumnModel().getColumn(1).setResizable(false);
            tbBeranda.getColumnModel().getColumn(2).setResizable(false);
            tbBeranda.getColumnModel().getColumn(3).setResizable(false);
            tbBeranda.getColumnModel().getColumn(4).setResizable(false);
            tbBeranda.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true), " Preview ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblFoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Detail Pengaduan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama :");

        txtNamaPengadu.setText("Nama Pengadu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tanggal Pengaduan :");

        txtTgl.setText("Tanggal Pengaduan");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));

        txtTanggapan.setColumns(20);
        txtTanggapan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTanggapan.setRows(5);
        txtTanggapan.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jScrollPane3.setViewportView(txtTanggapan);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Detail Tanggapan :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaPengadu))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(txtNamaPengadu)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTgl)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Beranda Pengaduan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Detail Pengaduan :");

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        txtPengaduan.setColumns(20);
        txtPengaduan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPengaduan.setRows(5);
        txtPengaduan.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jScrollPane2.setViewportView(txtPengaduan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 794, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBerandaMouseClicked
        // TODO add your handling code here:
        setLaporan();
        setFoto();
    }//GEN-LAST:event_tbBerandaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tbBeranda;
    private javax.swing.JLabel txtNamaPengadu;
    private javax.swing.JTextArea txtPengaduan;
    private javax.swing.JTextArea txtTanggapan;
    private javax.swing.JLabel txtTgl;
    // End of variables declaration//GEN-END:variables

    
}
