/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.MasyarakatKontrol;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author zubaidi
 */
public class DashboardPetugas extends javax.swing.JFrame {
    
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMM yyyy / HH:mm");
    Date date = new Date();
    ResultSet rs;
    MasyarakatKontrol mk;
    
    /**
     * Creates new form DashboardMasyarakatForm
     */
    public DashboardPetugas() {
        initComponents();
        mk = new MasyarakatKontrol();
        this.getContentPane().setBackground(new Color(204,204,204));
        labelTanggal.setText(sdf.format(date)+"WIB");
        this.Beranda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menuBeranda = new javax.swing.JLabel();
        menuPelaporan = new javax.swing.JLabel();
        menuProses = new javax.swing.JLabel();
        menuAkun = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelLevel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuRegistrasiPetugas = new javax.swing.JLabel();
        labelIDPetugas = new javax.swing.JLabel();
        desktopTarget = new DesktopPaneBackground();

        panelDashboard.setBackground(new java.awt.Color(102, 255, 0));

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDashboardLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(223, 223, 223))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel12)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISPEMA Dashboard");
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 7, 117));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("_");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM PELAPORAN MASYARAKAT ( Admin dan Petugas )");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("SISPEMA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selamat Datang :");

        labelTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTanggal.setText("jLabel3");

        menuBeranda.setForeground(new java.awt.Color(255, 255, 255));
        menuBeranda.setText("Beranda");
        menuBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBerandaMouseClicked(evt);
            }
        });

        menuPelaporan.setForeground(new java.awt.Color(255, 255, 255));
        menuPelaporan.setText("Tanggapi Pengaduan");
        menuPelaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPelaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPelaporanMouseClicked(evt);
            }
        });

        menuProses.setForeground(new java.awt.Color(255, 255, 255));
        menuProses.setText("Pengaduan Selesai");
        menuProses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProsesMouseClicked(evt);
            }
        });

        menuAkun.setForeground(new java.awt.Color(255, 255, 255));
        menuAkun.setText("Setting Akun");
        menuAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAkunMouseClicked(evt);
            }
        });

        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama");

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Logout");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("SMK SYafi'i Akrom Kota Pekalongan - UKK Rekayasa Perangkat Lunak 2019/2020");

        labelLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelLevel.setForeground(new java.awt.Color(255, 255, 255));
        labelLevel.setText("PETUGAS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Anda Login Sebagai:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");

        menuRegistrasiPetugas.setForeground(new java.awt.Color(255, 255, 255));
        menuRegistrasiPetugas.setText("Registrasi Petugas");
        menuRegistrasiPetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRegistrasiPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrasiPetugasMouseClicked(evt);
            }
        });

        labelIDPetugas.setForeground(new java.awt.Color(255, 255, 255));
        labelIDPetugas.setText("ID_petugas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menuBeranda)
                        .addGap(18, 18, 18)
                        .addComponent(menuPelaporan)
                        .addGap(18, 18, 18)
                        .addComponent(menuProses)
                        .addGap(18, 18, 18)
                        .addComponent(menuAkun)
                        .addGap(18, 18, 18)
                        .addComponent(menuRegistrasiPetugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIDPetugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLevel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(labelNama)
                    .addComponent(labelLevel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(labelIDPetugas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuBeranda)
                    .addComponent(menuPelaporan)
                    .addComponent(menuProses)
                    .addComponent(menuAkun)
                    .addComponent(jLabel5)
                    .addComponent(menuRegistrasiPetugas))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        desktopTarget.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopTargetLayout = new javax.swing.GroupLayout(desktopTarget);
        desktopTarget.setLayout(desktopTargetLayout);
        desktopTargetLayout.setHorizontalGroup(
            desktopTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        desktopTargetLayout.setVerticalGroup(
            desktopTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(desktopTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1040, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginAdminForm lf = new LoginAdminForm();
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void menuAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAkunMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            SettingAkunFormPetugas bfm = new SettingAkunFormPetugas();
            BasicInternalFrameTitlePane biftp = (BasicInternalFrameTitlePane)((BasicInternalFrameUI)bfm.getUI()).getNorthPane();
            bfm.remove(biftp);
            desktopTarget.remove(0);
            desktopTarget.add(bfm);
            bfm.setVisible(true);
            bfm.setMaximum(true);
            
            bfm.txtNIK.setEditable(true);
            
            menuBeranda.setForeground(Color.white);
            menuAkun.setForeground(Color.red);
            menuPelaporan.setForeground(Color.white);
            menuRegistrasiPetugas.setForeground(Color.white);
            menuProses.setForeground(Color.white);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DashboardPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuAkunMouseClicked

    private void menuPelaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelaporanMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            TanggapiLaporan bfm = new TanggapiLaporan();
            BasicInternalFrameTitlePane biftp = (BasicInternalFrameTitlePane)((BasicInternalFrameUI)bfm.getUI()).getNorthPane();
            bfm.remove(biftp);
            desktopTarget.remove(0);
            desktopTarget.add(bfm);
            bfm.setVisible(true);
            bfm.setMaximum(true);
            menuBeranda.setForeground(Color.white);
            menuAkun.setForeground(Color.white);
            menuRegistrasiPetugas.setForeground(Color.white);
            menuPelaporan.setForeground(Color.red);
            menuProses.setForeground(Color.white);
            
            bfm.labelidpetugas.setText(labelIDPetugas.getText());
            
            if(labelLevel.getText().equalsIgnoreCase("admin")){
                bfm.txtTanggapi.setEditable(false);
                String text = "Untuk saat ini, Anda Tidak Dapat Menanggapi Laporan Warga.";
                bfm.txtTanggapi.setText("Anda Login Sebagai Admin.\n"+text+"\nSilahkan Login Sebagai Petugas");
                bfm.txtTanggapi.setForeground(Color.red);
                bfm.btnSimpan.setEnabled(false);
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DashboardPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPelaporanMouseClicked

    private void menuBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBerandaMouseClicked
        try {
            // TODO add your handling code here:
            BerandaFormMasyarakat bfm = new BerandaFormMasyarakat();
            BasicInternalFrameTitlePane biftp = (BasicInternalFrameTitlePane)((BasicInternalFrameUI)bfm.getUI()).getNorthPane();
            bfm.remove(biftp);
            desktopTarget.remove(0);
            desktopTarget.add(bfm);
            bfm.setVisible(true);
            bfm.setMaximum(true);
//            while(rs.next()){
//                bfm.txtNIKB.setText(rs.getString("nik"));
//            }
            menuBeranda.setForeground(Color.red);
            menuAkun.setForeground(Color.white);
            menuPelaporan.setForeground(Color.white);
            menuRegistrasiPetugas.setForeground(Color.white);
            menuProses.setForeground(Color.white);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DashboardPetugas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_menuBerandaMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void menuProsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProsesMouseClicked
        // TODO add your handling code here:
        try {
            BerandaFormPetugas bfm = new BerandaFormPetugas();
            BasicInternalFrameTitlePane biftp = (BasicInternalFrameTitlePane)((BasicInternalFrameUI)bfm.getUI()).getNorthPane();
            bfm.remove(biftp);
            desktopTarget.remove(0);
            desktopTarget.add(bfm);
            bfm.setVisible(true);
            bfm.setMaximum(true);
            menuBeranda.setForeground(Color.white);
            menuAkun.setForeground(Color.white);
            menuPelaporan.setForeground(Color.white);
            menuRegistrasiPetugas.setForeground(Color.white);
            menuProses.setForeground(Color.red);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DashboardPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuProsesMouseClicked

    private void menuRegistrasiPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrasiPetugasMouseClicked
        // TODO add your handling code here:
        try {
            registrasiPetugas rgp = new registrasiPetugas();
            BasicInternalFrameTitlePane biftp = (BasicInternalFrameTitlePane)((BasicInternalFrameUI)rgp.getUI()).getNorthPane();
            rgp.remove(biftp);
            desktopTarget.remove(0);
            desktopTarget.add(rgp);
            rgp.setVisible(true);
            rgp.setMaximum(true);
            menuBeranda.setForeground(Color.white);
            menuAkun.setForeground(Color.white);
            menuPelaporan.setForeground(Color.white);
            menuProses.setForeground(Color.white);
            menuRegistrasiPetugas.setForeground(Color.red);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DashboardPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRegistrasiPetugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardPetugas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel labelIDPetugas;
    public javax.swing.JLabel labelLevel;
    public javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTanggal;
    public javax.swing.JLabel menuAkun;
    private javax.swing.JLabel menuBeranda;
    private javax.swing.JLabel menuPelaporan;
    private javax.swing.JLabel menuProses;
    public javax.swing.JLabel menuRegistrasiPetugas;
    private javax.swing.JPanel panelDashboard;
    // End of variables declaration//GEN-END:variables

    private void Beranda(){
        try {
            BantuanForm dfm = new BantuanForm();
            BasicInternalFrameTitlePane biftp = (BasicInternalFrameTitlePane)((BasicInternalFrameUI)dfm.getUI()).getNorthPane();
            dfm.remove(biftp);
            desktopTarget.add(dfm);
            dfm.setVisible(true);
            dfm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DashboardPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
