/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.PengaduanKontrol;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author zubaidi
 */
public class LaporanProsesFormMasyarakat extends javax.swing.JInternalFrame {
    
    PengaduanKontrol pk;
    DashboardMasyarakatForm dmf;
    Date date;
    int IDPengaduan;
    String tanggal, nik, isi, foto, status;
    File file;
    DefaultTableModel dtm;
    
    /**
     * Creates new form BerandaFormMasyarakat
     */
    public LaporanProsesFormMasyarakat() {
        initComponents();
        pk = new PengaduanKontrol();
        dmf = new DashboardMasyarakatForm();
        tbLaporanProses.getTableHeader().setBackground(new Color(0,49,163));
        tbLaporanProses.getTableHeader().setForeground(new Color(255,255,255));
        //this.tampilLaporanProses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        labelNamaFoto = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLaporanProses = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIsiLaporan = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLokasiFoto = new javax.swing.JTextField();
        btnUbahGambar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("DATA PENGADUAN DIPROSES");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true), " Preview ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        labelNamaFoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNamaFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNamaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(labelNamaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpan.setBackground(java.awt.Color.red);
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan Laporan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tbLaporanProses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "NIK", "ID Laporan", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLaporanProses.setRowHeight(25);
        tbLaporanProses.setRowMargin(0);
        tbLaporanProses.setSelectionBackground(new java.awt.Color(102, 255, 0));
        tbLaporanProses.setShowVerticalLines(false);
        tbLaporanProses.getTableHeader().setResizingAllowed(false);
        tbLaporanProses.getTableHeader().setReorderingAllowed(false);
        tbLaporanProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLaporanProsesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLaporanProses);
        if (tbLaporanProses.getColumnModel().getColumnCount() > 0) {
            tbLaporanProses.getColumnModel().getColumn(0).setResizable(false);
            tbLaporanProses.getColumnModel().getColumn(1).setResizable(false);
            tbLaporanProses.getColumnModel().getColumn(2).setResizable(false);
            tbLaporanProses.getColumnModel().getColumn(3).setResizable(false);
        }

        txtIsiLaporan.setColumns(20);
        txtIsiLaporan.setRows(5);
        jScrollPane2.setViewportView(txtIsiLaporan);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Tambah / Ganti Gambar");

        txtLokasiFoto.setEditable(false);
        txtLokasiFoto.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        btnUbahGambar.setBackground(java.awt.Color.red);
        btnUbahGambar.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahGambar.setText("Ubah Gambar");
        btnUbahGambar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUbahGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahGambarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtLokasiFoto)
                            .addComponent(btnUbahGambar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLokasiFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbahGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        this.updateLaporan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tbLaporanProsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLaporanProsesMouseClicked
        // TODO add your handling code here:
        this.setLaporan();
    }//GEN-LAST:event_tbLaporanProsesMouseClicked

    private void btnUbahGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahGambarActionPerformed
        // TODO add your handling code here:
        pilihGambar();
    }//GEN-LAST:event_btnUbahGambarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbahGambar;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNamaFoto;
    public javax.swing.JTable tbLaporanProses;
    private javax.swing.JTextArea txtIsiLaporan;
    private javax.swing.JTextField txtLokasiFoto;
    // End of variables declaration//GEN-END:variables
    
    private void tampilLaporanProses(){
        try {
            dtm = (DefaultTableModel) tbLaporanProses.getModel();
            dtm.setRowCount(0);
            this.aturTabel();
            pk.tampilLaporanProses(dtm, nik);
            tbLaporanProses.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanProsesFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void aturTabel(){
        tbLaporanProses.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbLaporanProses.getColumnModel().getColumn(0).setPreferredWidth(35);
        tbLaporanProses.getColumnModel().getColumn(1).setPreferredWidth(135);
        tbLaporanProses.getColumnModel().getColumn(2).setPreferredWidth(98);
        tbLaporanProses.getColumnModel().getColumn(3).setPreferredWidth(85);
    }
    
    private void setLaporan(){
        try {
            String idLaporan = tbLaporanProses.getValueAt(tbLaporanProses.getSelectedRow(), 2).toString();
            ResultSet rs = pk.setLaporan(idLaporan);
            while(rs.next()){
                txtIsiLaporan.setText(rs.getString("isi_laporan"));
                labelNamaFoto.setText(rs.getString("foto"));
            }
            this.setFoto();
        } catch (SQLException ex) {
            Logger.getLogger(LaporanProsesFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setFoto(){
        try {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            String path = new File(".").getCanonicalPath();
            Image image = toolkit.getImage(path+"/image/"+labelNamaFoto.getText());
            Image ImageResize = image.getScaledInstance(235, 275, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(ImageResize);
            labelFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(LaporanProsesFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void pilihGambar(){
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Image", "jpg", "png"));
        if(fileChooser.showOpenDialog(labelFoto) == JFileChooser.APPROVE_OPTION){
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image image = toolkit.getImage(fileChooser.getSelectedFile().getAbsolutePath());
            Image imageResize = image.getScaledInstance(235, 275, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(imageResize);
            labelFoto.setIcon(icon);
            labelNamaFoto.setText(fileChooser.getSelectedFile().getName());
            txtLokasiFoto.setText(fileChooser.getSelectedFile().getPath());
            file = new File(fileChooser.getSelectedFile().getPath());
        }
    }
    

    private void updateLaporan(){
        try {
            int row = tbLaporanProses.getSelectedRow();
            IDPengaduan = Integer.parseInt(tbLaporanProses.getValueAt(row, 2).toString());
            tanggal = (String) tbLaporanProses.getValueAt(row, 3);
            nik = (String) tbLaporanProses.getValueAt(row, 1);
            
            isi = txtIsiLaporan.getText();
            foto = labelNamaFoto.getText();
            
            int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "yakin mau ubah data ini ?", "konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION);
            
            if (konfirmasi == 0) {
                pk.updatePengaduan(IDPengaduan, isi, foto);
                
                String path = new File(".").getCanonicalPath();
                FileUtils.copyToDirectory(file, new File(path+"/image"));
                JOptionPane.showMessageDialog(rootPane, "Laporan Berhasil  Disimpan.\nCek Laporan di Menu Laporan Selesai");
            }
            
            
            
            
            this.resetLaporan();
            this.tampilLaporanProses();
        } catch (IOException ex) {
            Logger.getLogger(LaporanProsesFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanProsesFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void resetLaporan(){
        this.tampilLaporanProses();
        txtIsiLaporan.setText(null);
        labelNamaFoto.setText(null);
        labelFoto.setIcon(null);
        labelFoto.revalidate();
        txtLokasiFoto.setText(null);
        btnUbahGambar.setEnabled(true);
        dtm.removeRow(0);
        tbLaporanProses.setModel(dtm);
    }
    
}
