/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.PengaduanKontrol;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zubaidi
 */
public class LaporanSelesaiFormMasyarakat extends javax.swing.JInternalFrame {
    
    PengaduanKontrol pk;
    DashboardMasyarakatForm dmf;
    Date date;
    int IDPengaduan;
    String tanggal, nik, isi, foto, status;
    File file;
    
    /**
     * Creates new form BerandaFormMasyarakat
     */
    public LaporanSelesaiFormMasyarakat() {
        initComponents();
        pk = new PengaduanKontrol();
        dmf = new DashboardMasyarakatForm();
        tbLaporanSelesai.getTableHeader().setBackground(new Color(0,49,163));
        tbLaporanSelesai.getTableHeader().setForeground(new Color(255,255,255));    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLaporanSelesai = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIsiLaporan = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("DATA PENGADUAN SELESAI");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true), " Preview ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbLaporanSelesai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "NIK", "ID Laporan", "Tanggal", "Gambar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLaporanSelesai.setRowHeight(25);
        tbLaporanSelesai.setRowMargin(0);
        tbLaporanSelesai.setSelectionBackground(new java.awt.Color(102, 255, 0));
        tbLaporanSelesai.setShowVerticalLines(false);
        tbLaporanSelesai.getTableHeader().setResizingAllowed(false);
        tbLaporanSelesai.getTableHeader().setReorderingAllowed(false);
        tbLaporanSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLaporanSelesaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLaporanSelesai);
        if (tbLaporanSelesai.getColumnModel().getColumnCount() > 0) {
            tbLaporanSelesai.getColumnModel().getColumn(0).setResizable(false);
            tbLaporanSelesai.getColumnModel().getColumn(1).setResizable(false);
            tbLaporanSelesai.getColumnModel().getColumn(2).setResizable(false);
            tbLaporanSelesai.getColumnModel().getColumn(3).setResizable(false);
            tbLaporanSelesai.getColumnModel().getColumn(4).setResizable(false);
        }

        txtIsiLaporan.setEditable(false);
        txtIsiLaporan.setColumns(20);
        txtIsiLaporan.setRows(5);
        jScrollPane2.setViewportView(txtIsiLaporan);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(java.awt.Color.red);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("LAPORAN YANG BERSTATUS SELESAI TIDAK DAPAT DIUBAH");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cari ID Laporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLaporanSelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLaporanSelesaiMouseClicked
        // TODO add your handling code here:
        this.setLaporan();
    }//GEN-LAST:event_tbLaporanSelesaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelFoto;
    public javax.swing.JTable tbLaporanSelesai;
    private javax.swing.JTextArea txtIsiLaporan;
    // End of variables declaration//GEN-END:variables
    /*
    private void tampilLaporanProses(){
        try {
            DefaultTableModel dtm = (DefaultTableModel) tbLaporanSelesai.getModel();
            dtm.setRowCount(0);
            this.aturTabel();
            
            
            pk.tampilLaporanSelesai(dtm);
            tbLaporanSelesai.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanSelesaiFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    */
    private void aturTabel(){
        tbLaporanSelesai.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbLaporanSelesai.getColumnModel().getColumn(0).setPreferredWidth(35);
        tbLaporanSelesai.getColumnModel().getColumn(1).setPreferredWidth(205);
        tbLaporanSelesai.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbLaporanSelesai.getColumnModel().getColumn(3).setPreferredWidth(90);
        tbLaporanSelesai.getColumnModel().getColumn(4).setPreferredWidth(180);
    }
    
    private void setLaporan(){
        try {
            String idLaporan = tbLaporanSelesai.getValueAt(tbLaporanSelesai.getSelectedRow(), 2).toString();
            ResultSet rs = pk.setLaporan(idLaporan);
            while(rs.next()){
                txtIsiLaporan.setText(rs.getString("isi_laporan"));
            }
            this.setFoto();
        } catch (SQLException ex) {
            Logger.getLogger(LaporanSelesaiFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setFoto(){
        try {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            String path = new File(".").getCanonicalPath();
            Image image = toolkit.getImage(path+"/image/"+tbLaporanSelesai.getValueAt(tbLaporanSelesai.getSelectedRow(), 4));
            Image ImageResize = image.getScaledInstance(235, 275, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(ImageResize);
            labelFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(LaporanSelesaiFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
    private void pilihGambar(){
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Image", "jpg", "png"));
        if(fileChooser.showOpenDialog(labelFoto) == JFileChooser.APPROVE_OPTION){
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image image = toolkit.getImage(fileChooser.getSelectedFile().getAbsolutePath());
            Image imageResize = image.getScaledInstance(235, 275, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(imageResize);
            labelFoto.setIcon(icon);
            labelNamaFoto.setText(fileChooser.getSelectedFile().getName());
            file = new File(fileChooser.getSelectedFile().getPath());
        }
    }
    
    private void hapusGambar(){
        file = new File("image/"+labelNamaFoto.getText());
        file.delete();
        labelNamaFoto.setText("");
        labelFoto.setIcon(null);
        labelFoto.revalidate();
    }
    
    
    private void resetLaporan(){
        this.tampilLaporanProses();
        txtIsiLaporan.setText(null);
        labelNamaFoto.setText(null);
        labelFoto.setIcon(null);
        labelFoto.revalidate();
    }
    */
}
