/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.MasyarakatKontrol;
import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.PetugasKontrol;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zubaidi
 */
public class registrasiPetugas extends javax.swing.JInternalFrame {
    
    PetugasKontrol pk;
    int idPetugas;
    String nama, username, pass, telp;
    
    /**
     * Creates new form BerandaFormMasyarakat
     */
    public registrasiPetugas() {
        initComponents();
        pk = new PetugasKontrol();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoTlp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnsIMPAN = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1040, 450));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRASI PETUGAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Petugas");

        txtIdP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdP.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));
        txtIdP.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNama.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No. Telefon");

        txtNoTlp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNoTlp.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));
        txtNoTlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoTlpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoTlpKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Password");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        btnsIMPAN.setBackground(java.awt.Color.red);
        btnsIMPAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsIMPAN.setForeground(new java.awt.Color(255, 255, 255));
        btnsIMPAN.setText("SIMPAN");
        btnsIMPAN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsIMPAN.setBorderPainted(false);
        btnsIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsIMPANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassword)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNoTlp)
                                    .addComponent(txtNama)
                                    .addComponent(txtIdP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btnsIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnsIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTlpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTlpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTlpKeyReleased

    private void btnsIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsIMPANActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_btnsIMPANActionPerformed

    private void txtNoTlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTlpKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNoTlpKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTlp;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
    
    private void setEditable(boolean b){
        txtNama.setEditable(b);
        txtNoTlp.setEditable(b);
        txtUsername.setEditable(b);
        txtPassword.setEditable(b);
    }
    
    private void simpan(){
        idPetugas = Integer.parseInt(txtIdP.getText().toString());
        nama = txtNama.getText();
        username = txtUsername.getText();
        pass = txtPassword.getText();
        telp = txtNoTlp.getText();
        
        try {
            pk.simpanDataPetugas(idPetugas, nama, username, pass, telp);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Diubah");
            this.setResetObjek();
//            this.setEditable(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data Petugas Berhasil Ditambahkan");
            Logger.getLogger(registrasiPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setResetObjek() {
        txtIdP.setText(null);
        txtNama.setText(null);
        txtNoTlp.setText(null);
        txtUsername.setText(null);
        txtPassword.setText(null);
    }
    
}
