/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.TanggapiLaporanKontrol;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zubaidi
 */
public class TanggapiLaporan extends javax.swing.JInternalFrame {
    
    TanggapiLaporanKontrol tl;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat tgp = new SimpleDateFormat("HHmmms");
    Date date = new Date();
    ResultSet rs;
    int idTanggapan, idPengaduan, idPetugas;
    String tanggal, tanggapan;
    
    /**
     * Creates new form BerandaFormMasyarakat
     */
    public TanggapiLaporan() {
        initComponents();
        tl = new TanggapiLaporanKontrol();
        tbLaporanMasuk.getTableHeader().setBackground(new Color(0,49,163));
        tbLaporanMasuk.getTableHeader().setForeground(new Color(255,255,255));
        labelTanggal.setText(sdf.format(date));
        this.tampilLaporan();
        this.autoID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLaporanMasuk = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        labelNamaFoto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIsiLaporan = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTanggapi = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        labelTanggal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNoTanggapan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelidpetugas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 450));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Cari ID Laporan");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 1, true));

        tbLaporanMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID Laporan", "NIK", "Nama Pelapor", "Tanggal Laporan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLaporanMasuk.setRowHeight(25);
        tbLaporanMasuk.setRowMargin(0);
        tbLaporanMasuk.setSelectionBackground(new java.awt.Color(255, 82, 49));
        tbLaporanMasuk.setShowVerticalLines(false);
        tbLaporanMasuk.getTableHeader().setResizingAllowed(false);
        tbLaporanMasuk.getTableHeader().setReorderingAllowed(false);
        tbLaporanMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLaporanMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLaporanMasuk);
        if (tbLaporanMasuk.getColumnModel().getColumnCount() > 0) {
            tbLaporanMasuk.getColumnModel().getColumn(0).setResizable(false);
            tbLaporanMasuk.getColumnModel().getColumn(1).setResizable(false);
            tbLaporanMasuk.getColumnModel().getColumn(2).setResizable(false);
            tbLaporanMasuk.getColumnModel().getColumn(3).setResizable(false);
            tbLaporanMasuk.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 1, true), " Preview ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        labelNamaFoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNamaFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNamaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(labelNamaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 1, true));

        txtIsiLaporan.setEditable(false);
        txtIsiLaporan.setColumns(20);
        txtIsiLaporan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIsiLaporan.setLineWrap(true);
        txtIsiLaporan.setRows(5);
        txtIsiLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane2.setViewportView(txtIsiLaporan);

        jScrollPane3.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 1, true));

        txtTanggapi.setColumns(20);
        txtTanggapi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTanggapi.setLineWrap(true);
        txtTanggapi.setRows(5);
        txtTanggapi.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane3.setViewportView(txtTanggapi);

        btnSimpan.setBackground(java.awt.Color.blue);
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Kirim");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        labelTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTanggal.setForeground(java.awt.Color.blue);
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTanggal.setText("yyyy-MM-dd");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("Tanggal Balas Laporan:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("No. Tanggapan:");

        labelNoTanggapan.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        labelNoTanggapan.setForeground(java.awt.Color.blue);
        labelNoTanggapan.setText("jLabel4");

        jSeparator1.setBackground(java.awt.Color.blue);
        jSeparator1.setForeground(java.awt.Color.blue);

        jLabel4.setText("tanggapan petugas");

        jLabel5.setText("pengaduan masyarakat");

        labelidpetugas.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNoTanggapan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelidpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggal)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(labelNoTanggapan)
                    .addComponent(labelidpetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(418, 418, 418))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLaporanMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLaporanMasukMouseClicked
        // TODO add your handling code here:
        this.tampilIsiLaporan();
    }//GEN-LAST:event_tbLaporanMasukMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        this.simpanTanggapan();
        reset();
        this.autoID();
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNamaFoto;
    private javax.swing.JLabel labelNoTanggapan;
    private javax.swing.JLabel labelTanggal;
    public javax.swing.JLabel labelidpetugas;
    private javax.swing.JTable tbLaporanMasuk;
    private javax.swing.JTextArea txtIsiLaporan;
    public javax.swing.JTextArea txtTanggapi;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        labelFoto.setIcon(null);
        labelFoto.revalidate();
        labelNamaFoto.setText(null);
        txtIsiLaporan.setText(null);
        txtTanggapi.setText(null);
//        autoID();
    }
    
    private void tampilLaporan() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tbLaporanMasuk.getModel();
            dtm.setRowCount(0);
            tl.tampilLaporan(dtm);
            tbLaporanMasuk.setModel(dtm);
            aturTabel();
        } catch (SQLException ex) {
            Logger.getLogger(TanggapiLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampilIsiLaporan(){
        try {
            rs = tl.setLaporan(tbLaporanMasuk.getValueAt(tbLaporanMasuk.getSelectedRow(), 1).toString());
            while(rs.next()){
                labelNamaFoto.setText(rs.getString("foto"));
                txtIsiLaporan.setText(rs.getString("isi_laporan"));
            }
            this.setFoto();
        } catch (SQLException ex) {
            Logger.getLogger(TanggapiLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setFoto(){
        try {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            String path = new File(".").getCanonicalPath();
            Image image = toolkit.getImage(path+"/image/"+labelNamaFoto.getText());
            Image ImageResize = image.getScaledInstance(235, 275, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(ImageResize);
            labelFoto.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(LaporanSelesaiFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void aturTabel(){
        tbLaporanMasuk.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbLaporanMasuk.getColumnModel().getColumn(0).setPreferredWidth(35);
        tbLaporanMasuk.getColumnModel().getColumn(1).setPreferredWidth(105);
        tbLaporanMasuk.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbLaporanMasuk.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbLaporanMasuk.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    private void simpanTanggapan() {
        idTanggapan = Integer.parseInt(labelNoTanggapan.getText()); 
        idPengaduan = Integer.parseInt(tbLaporanMasuk.getValueAt(tbLaporanMasuk.getSelectedRow(), 1).toString()); 
        idPetugas = Integer.parseInt(labelidpetugas.getText());
        tanggal = labelTanggal.getText();
        tanggapan = txtTanggapi.getText();
        try {
            tl.simpanTanggapan(idTanggapan, idPengaduan, tanggal, tanggapan, idPetugas);
            tl.updatestatus(idPengaduan);
            tampilLaporan();
            JOptionPane.showMessageDialog(rootPane, "Tanggapan Berhasil Dikirim");
        } catch (SQLException ex) {
            Logger.getLogger(TanggapiLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void autoID(){
        labelNoTanggapan.setText(String.valueOf(new SimpleDateFormat("ddHHmmss").format(new Date())));
    }
}
