/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ukk.aplikasi.pengaduan.masyarakat.form;

import com.ukk.aplikasi.pengaduan.masyarakat.kontrol.PengaduanKontrol;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author zubaidi
 */
public class UploadLaporanFormMasyarakat extends javax.swing.JInternalFrame {
    
    PengaduanKontrol pk;
    DashboardMasyarakatForm dmf;
    File file;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat sdfID = new SimpleDateFormat("hmmss");
    Date date = new Date();
    int IDPengaduan;
    String tanggal, nik, isi, foto, status;
    
    /**
     * Creates new form BerandaFormMasyarakat
     */
    public UploadLaporanFormMasyarakat() {
        initComponents();
        pk = new PengaduanKontrol();
        dmf = new DashboardMasyarakatForm();
        txtNIK.setText(dmf.labelNIK.getText());
        labeltanggal.setText(sdf.format(date));
//        date = new Date();
//        this.setTanggal();
        this.reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDPengaduan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLaporan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtLokasiFoto = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        labelNamaFoto = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("KIRIM LAPORAN PENGADUAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Laporan");

        txtIDPengaduan.setEditable(false);
        txtIDPengaduan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIDPengaduan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIDPengaduan.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Isi Laporan");

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        txtLaporan.setColumns(20);
        txtLaporan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLaporan.setLineWrap(true);
        txtLaporan.setRows(5);
        txtLaporan.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));
        jScrollPane2.setViewportView(txtLaporan);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Foto");

        txtLokasiFoto.setEditable(false);
        txtLokasiFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLokasiFoto.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        btnCari.setBackground(java.awt.Color.red);
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Pilih");
        btnCari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCari.setBorderPainted(false);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true), " Preview ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        labelNamaFoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNamaFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNamaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(labelNamaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpan.setBackground(java.awt.Color.red);
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan Laporan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Laporan");

        txtNIK.setEditable(false);
        txtNIK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNIK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNIK.setText("jTextField1");
        txtNIK.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 1, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("NIK");

        labeltanggal.setText("tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(416, 533, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLokasiFoto)
                                        .addGap(10, 10, 10)))
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(txtIDPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNIK)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(labeltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLokasiFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        this.pilihGambar();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        this.simpanLaporan();
//        this.reset();
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNamaFoto;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField txtIDPengaduan;
    private javax.swing.JTextArea txtLaporan;
    private javax.swing.JTextField txtLokasiFoto;
    public javax.swing.JTextField txtNIK;
    // End of variables declaration//GEN-END:variables
    
    private void pilihGambar(){
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Image", "jpg", "png"));
        if(fileChooser.showOpenDialog(labelFoto) == JFileChooser.APPROVE_OPTION){
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image image = toolkit.getImage(fileChooser.getSelectedFile().getAbsolutePath());
            Image imageResize = image.getScaledInstance(235, 275, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(imageResize);
            labelFoto.setIcon(icon);
            labelNamaFoto.setText(fileChooser.getSelectedFile().getName());
            txtLokasiFoto.setText(fileChooser.getSelectedFile().getPath());
            file = new File(fileChooser.getSelectedFile().getPath());
        }
    }
    
    private void simpanLaporan(){
        IDPengaduan = Integer.parseInt(txtIDPengaduan.getText());
        tanggal = labeltanggal.getText();
        nik = txtNIK.getText();
        isi = txtLaporan.getText();
        foto = labelNamaFoto.getText();
        try {
            pk.simpanPengaduan(IDPengaduan, tanggal, nik, isi, foto);
            reset();
            JOptionPane.showMessageDialog(rootPane, "Laporan Berhasil Disimpan");
            String path = new File(".").getCanonicalPath();
            FileUtils.copyToDirectory(file, new File(path+"/image"));
        } catch (SQLException ex) {
            Logger.getLogger(UploadLaporanFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UploadLaporanFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void reset() {
//        this.setTanggal();
        this.setAutoID();
        txtLaporan.setText(null);
        txtLokasiFoto.setText(null);
        labelFoto.setIcon(null);
        labelFoto.revalidate();
        labelNamaFoto.setText(null);
    }

//    private void setTanggal() {
//        dateLaporan.setDate(date);
//        JTextFieldDateEditor editor = (JTextFieldDateEditor) dateLaporan.getDateEditor();
//        editor.setEditable(false);
//    }

    private void setAutoID() {
        dmf = new DashboardMasyarakatForm();
        try {
            ResultSet rs = pk.setAutoID();
            while(rs.next()){
                if(rs.first() == false){
                    txtIDPengaduan.setText(sdfID.format(date)+"0001");
                }else{
                    rs.last();
                    int no = rs.getInt(1)+1;
                    String idP = String.valueOf(no);
                    int noID = idP.length();
                    for(int a = 0; a<4-noID; a++){
                        idP = "0"+idP;
                    }
                    txtIDPengaduan.setText(sdfID.format(date)+idP);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(UploadLaporanFormMasyarakat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
